name: Build on PR

on:
  pull_request:
    branches: [ master, develop ]

jobs:

  build:
    runs-on: ubuntu-latest
    timeout-minutes: 30

    steps:

      - name: Checkout the project
        uses: actions/checkout@master
      
      - name: Install dependancies
        run: |
          echo "starting docker build"
          cd repo_pkg
          docker build -t parallel-test .
          docker run parallel test
